# Generated by Django 4.0.3 on 2022-04-28 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_photozonedata_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photozonedata',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 5, 45, 29, 686454, tzinfo=utc)),
        ),
    ]
