# Generated by Django 4.0.3 on 2022-05-01 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_alter_photozonedata_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photozonedata',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 11, 47, 17, 964107, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='StatisticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField()),
                ('datetime', models.TextField()),
                ('angry_percent', models.IntegerField()),
                ('disgusted_percent', models.IntegerField()),
                ('fearful_percent', models.IntegerField()),
                ('happy_percent', models.IntegerField()),
                ('neutral_percent', models.IntegerField()),
                ('sad_percent', models.IntegerField()),
                ('surprised_percent', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photozone_statistics_data_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
