# Generated by Django 4.0.3 on 2022-05-04 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_photozonedata_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photozonedata',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 8, 41, 25, 196831, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='StatisticsData',
        ),
    ]
