# Generated by Django 4.0.3 on 2022-05-05 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_photozonedata_create_date_shareemotion_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photozonedata',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 8, 58, 50, 168734, tzinfo=utc)),
        ),
    ]
