# Generated by Django 4.0.3 on 2022-05-05 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_photozonedata_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareemotion',
            name='share_emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.photozonedata'),
        ),
        migrations.AlterField(
            model_name='photozonedata',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 12, 32, 962020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shareemotion',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 12, 32, 962020, tzinfo=utc)),
        ),
    ]
